Repository Kathybui732/Crate, pull requests merged in 2020-10, with the labels that each got.

#9 Install and configure Redux dev tools
  code/api/package-lock.json
  code/api/package.json
  code/web/package-lock.json
  code/web/package.json
  code/web/src/setup/store.js
Labels: FE

#6 Documentation templates
  README.md
  pull-request-template.md
Labels: documentation

#47 Profile photo/rebase
  code/api/.gitignore
  code/api/jest.config.js
  code/api/package-lock.json
  code/api/package.json
  code/api/src/config/database.json
  code/api/src/migrations/1-user.js
  code/api/src/modules/user/model.js
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/resolvers.js
  code/api/src/modules/user/types.js
  code/api/tests/user_update_mutation.test.js
  code/package.json
  code/web/public/images/profile.png
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/ProfilePicture.js
  code/web/src/modules/user/api/actions.js
Labels: FE, deliverable, feature

#48 B 2 testing
  code/api/package.json
  code/api/src/config/database.json
  code/api/src/config/params.json
  code/api/src/migrations/1-user.js
  code/api/src/modules/user/model.js
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/resolvers.js
  code/api/src/modules/user/types.js
  code/api/src/tests/modules/user/mutations.test.js
  code/api/tests/user_update_mutation.test.js
Labels: BE, User Story 1, User Story 2, User Story 3, User Story 4, User Story 5, feature, testing

#55 User's kept products
  code/api/src/migrations/20201016010413-create-user-product.js
  code/api/src/modules/user/resolvers.js
  code/api/src/modules/userProduct/model.js
  code/api/src/modules/userProduct/query.js
  code/api/src/modules/userProduct/resolvers.js
  code/api/src/modules/userProduct/types.js
  code/api/src/seeders/4-userProducts.js
Labels: BE, User Story 7, feature

#57 Persist user profile edits to database
  code/web/package-lock.json
  code/web/src/modules/user/OrderHistory.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/ProfilePicture.js
  code/web/src/modules/user/api/actions.js
  code/web/src/ui/Form/Form.js
  code/web/src/ui/input/Textarea.js
Labels: BE, FE, bug, enhancement, feature

#63 Fix bug
  code/api/src/modules/user/resolvers.js
Labels: BE, feature, testing
